"""The Agent entity: durable identity/configuration plus one liveness model.

Public seam for the delivery line (design §5.2) is exactly two names —
:func:`local_actors` and :func:`verify_fetch_claim`.  Nothing outside this
package composes an agent identity.
"""

from hyprial.identity.impl.agents.state.liveness import (
    AGENT_HEARTBEAT_TTL_SECONDS,
    RUNTIME_HEADLESS,
    RUNTIME_INTERACTIVE,
    AgentAlreadyRunning,
    AgentBinding,
    AgentLiveness,
)
from hyprial.identity.impl.agents.actor._core import AgentActor, AgentRegistryActor
from hyprial.identity.impl.agents.actor._base import SenderIdentityError
from hyprial.identity.impl.agents.home.config import (
    NATIVE_CONFIG_MAPPING_VERSION,
    AgentConfig,
    AgentConfigError,
    ConfigManifest,
    ConfigManifestItem,
    ConfigProjectionReceipt,
    NativeConfigProjection,
    NativeProjectionItem,
    build_native_projection,
    materialize_native_projection,
    normalize_agent_config,
    require_agent_config,
    validate_agent_config_location,
    verify_native_projection,
)
from hyprial.identity.impl.agents.home.environment import (
    BASE_CHILD_ENVIRONMENT_NAMES,
    GENERATED_CHILD_ENVIRONMENT_NAMES,
    P2_CONTROLLED_ENVIRONMENT_NAMES,
    CompleteChildEnvironment,
    apply_runtime_environment_profile,
    build_complete_child_environment,
    resolve_agent_secrets,
)
from hyprial.identity.impl.agents.runtime.context import (
    AgentRuntimeContext,
    AgentRuntimeError,
    AgentRuntimeRoots,
    AgentToolProfile,
    DEFAULT_AGENT_TOOL_PROFILE,
    SshToolAuthorization,
    resolve_agent_runtime_context,
)
from hyprial.identity.impl.agents.home.provisioner import AgentHomeError, AgentHomeProvisioner, HomeReceipt
from hyprial.identity.impl.agents.runtime.secrets import (
    ResolvedSecret,
    SECRET_ENVIRONMENT_NAMES,
    SecretCatalogEntry,
    SecretCustody,
    SecretGrant,
    SecretResolver,
    SecretResolutionError,
    SecretSource,
)
from hyprial.identity.impl.agents.registry._base import (
    ACTOR_NAME_PATTERN,
    Agent,
    AgentBlock,
    AgentError,
    AgentExistsError,
    AgentNotFoundError,
    HandoverNotice,
    InvalidAgentNameError,
    PinConflictError,
    RestoreDisposition,
    normalize_capabilities,
    normalize_harness_args,
    normalize_pinned_adapters,
    )
from hyprial.identity.impl.agents.registry._core import (
    AgentRegistry,
    default_registry,
    local_actors,
    set_default_registry,
    verify_fetch_claim,
)
from hyprial.identity.impl.agents.migration._base import (
    AgentHomeMigrationError,
    AgentMigrationAuthorization,
    AgentMigrationPlan,
    MigrationEntry,
    MigrationPhase,
    MigrationRecord,
    SupportKey,
    SupportMatrix,
    SupportRow,
    SupportStatus,
)
from hyprial.identity.impl.agents.migration._bindings import (
    AgentMigrationBindings,
    AgentMigrationLivenessProbe,
    AgentRuntimeMigrationBindings,
    )
from hyprial.identity.impl.agents.migration.coordinator import (
    AgentMigrationCoordinator,
    )

__all__ = [
    "ACTOR_NAME_PATTERN",
    "AGENT_HEARTBEAT_TTL_SECONDS",
    "RUNTIME_HEADLESS",
    "RUNTIME_INTERACTIVE",
    "Agent",
    "AgentBlock",
    "AgentActor",
    "AgentAlreadyRunning",
    "AgentBinding",
    "AgentConfig",
    "AgentConfigError",
    "AgentError",
    "AgentExistsError",
    "AgentHomeError",
    "AgentHomeMigrationError",
    "AgentHomeProvisioner",
    "AgentLiveness",
    "AgentNotFoundError",
    "AgentMigrationAuthorization",
    "AgentMigrationBindings",
    "AgentMigrationCoordinator",
    "AgentMigrationLivenessProbe",
    "AgentMigrationPlan",
    "AgentRuntimeMigrationBindings",
    "AgentRegistry",
    "AgentRegistryActor",
    "AgentRuntimeContext",
    "AgentRuntimeError",
    "AgentRuntimeRoots",
    "AgentToolProfile",
    "BASE_CHILD_ENVIRONMENT_NAMES",
    "CompleteChildEnvironment",
    "ConfigManifest",
    "ConfigManifestItem",
    "ConfigProjectionReceipt",
    "GENERATED_CHILD_ENVIRONMENT_NAMES",
    "P2_CONTROLLED_ENVIRONMENT_NAMES",
    "HandoverNotice",
    "HomeReceipt",
    "InvalidAgentNameError",
    "NATIVE_CONFIG_MAPPING_VERSION",
    "NativeConfigProjection",
    "NativeProjectionItem",
    "MigrationEntry",
    "MigrationPhase",
    "MigrationRecord",
    "PinConflictError",
    "RestoreDisposition",
    "DEFAULT_AGENT_TOOL_PROFILE",
    "ResolvedSecret",
    "RestoreDisposition",
    "SECRET_ENVIRONMENT_NAMES",
    "SecretCatalogEntry",
    "SecretCustody",
    "SecretGrant",
    "SecretResolutionError",
    "SecretResolver",
    "SecretSource",
    "SshToolAuthorization",
    "SenderIdentityError",
    "apply_runtime_environment_profile",
    "SupportKey",
    "SupportMatrix",
    "SupportRow",
    "SupportStatus",
    "build_complete_child_environment",
    "resolve_agent_secrets",
    "build_native_projection",
    "default_registry",
    "local_actors",
    "materialize_native_projection",
    "normalize_agent_config",
    "require_agent_config",
    "normalize_capabilities",
    "normalize_harness_args",
    "normalize_pinned_adapters",
    "resolve_agent_runtime_context",
    "set_default_registry",
    "validate_agent_config_location",
    "verify_fetch_claim",
    "verify_native_projection",
]
