"""generated by scripts/refactor: extracted symbols identity_slug from src/hyprial/squire/setup.py."""

import re



def identity_slug(value: str) -> str:
    """A host-side lookup-key slug for an identity segment (owner/machine).

    ``owner_key``/``machine_key`` are not credentials: they are dict keys for
    the binding store and components of the squire session reference
    (``squire:<owner_key>:<machine_key>``), so a deterministic normalization
    of the identity they label is a sound default for them.
    """

    slug = re.sub(r"[^a-z0-9._-]+", "-", value.strip().lower()).strip("-")
    if not slug:
        raise ValueError(f"cannot derive a lookup key from {value!r}")
    return slug
