"""generated by scripts/refactor: extracted symbols Capability, SupportLevel from src/hyprial/harnesses/capabilities.py."""

from enum import StrEnum



class Capability(StrEnum):
    INTERACTIVE_ATTACH = "interactive_attach"  # TUI attach + daemon registration
    HEADLESS_EXEC = "headless_exec"  # managed delivery -> one turn -> result
    WAKE_PUSH = "wake_push"  # daemon can wake a live session
    PROACTIVE_SEND = "proactive_send"  # in-session agent can send out (harness_send)
    SESSION_LIFECYCLE = "session_lifecycle"  # fixed session id / resume / fork
    TOOL_INJECTION = "tool_injection"  # hyprial toolset injected and pre-authorized
    PLUGIN_INJECTION = "plugin_injection"  # HYPRIAL_HOME session plugin payloads
    TURN_CONTROL = "turn_control"  # interrupt (steer/follow_up optional supersets)
    EVENT_STREAM = "event_stream"  # structured events (completion, observability)
    MODEL_SELECT = "model_select"  # provider+model and endpoint selection



class SupportLevel(StrEnum):
    NATIVE = "native"
    DEGRADED = "degraded"
    UNSUPPORTED = "unsupported"
