"""generated by scripts/refactor: extracted symbols DEADLINE_NODE, STATE_DONE, STATE_ESCALATED, WORK_NODE, operation_key from src/hyprial/routine/pac_dispatch.py."""

DEADLINE_NODE = "deadline"

STATE_DONE = "done"

STATE_ESCALATED = "escalated"

WORK_NODE = "work"



def operation_key(
    routine_name: str, task_uuid: str, occurrence_slot_ms: int | None = None
) -> str:
    base = f"routine:{routine_name}:{task_uuid}"
    return base if occurrence_slot_ms is None else f"{base}:{occurrence_slot_ms}"
