"""generated by scripts/refactor: extracted symbols OFFICIAL_GIT_URL, FORGEJO_GIT_URL, DEFAULT_GIT_URL from src/hyprial/updates.py."""

OFFICIAL_GIT_URL = "https://github.com/Hyprial/hyprial.git"

FORGEJO_GIT_URL = "ssh://git@git.internal.hyprial.com/HyprialOS/harness-bridge.git"

DEFAULT_GIT_URL = FORGEJO_GIT_URL
